### ISSUE TITLE
怎么修改外部缩略图的大小？

### ISSUE THREAD

**Issue by wTao-Yang** [LS1231/vue-preview#48]
以前是img标签，现在封装成组件了，怎么修改？

**Comment by Rodkovic** [comment]
修改样式就可以了
用scss修改的
```scss
.my-gallery {
  img {
    width: 100px;
    height: 100px;
    box-shadow:0 0 8px #999;
  }
  figure {
    margin: 9px;
    width: 100px;
    display: inline-block;
  }
}
```
